# action.yml
name: 'Hdiv Vuln Checker'
description: 'Find vulnearbilities'
runs:
  using: 'composite'
  steps:
    - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      shell: bash
    - run: echo "The workflow is now ready to test your code on the runner."
      shell: bash
    - run: ls -al
      shell: bash
    - run: docker-compose up -d
      shell: bash
