# action.yml
name: 'Hdiv Vuln Checker'
description: 'Find vulnearbilities'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  post-entrypoint: 'check-status.sh'
