version: "3.9"
services:
  vulnchecker:
    build: .
    volumes:
        - ./data:/mnt/data
    environment:
        hdiv.build.init: "${BUILD_INIT}"
        hdiv.build.end: "${BUILD_END}"
        hdiv.application.name: "${APPLICATION_NAME}"
        hdiv.application.version : "${APPLICATION_VERSION}"
        hdiv.triggers: "${TRIGGERS}"
        hdiv.triggers.vulnerable.libraries: "${TRIGGERS_VULNERABLE_DEPENDENCIES}"
        hdiv.connection.name: "${CONNECTION_NAME}"
        hdiv.resource.folder: "/mnt/data"