on: [push]

jobs:
  hdiv_vuln_checker:
    runs-on: ubuntu-latest
    name: Hdiv vulnerabilities check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Hdiv vulnerabilities check step
        uses: ./vuln-checker-action
        id: hdiv_vuln_checker
