on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  hdiv_vuln_checker:
    runs-on: ubuntu-latest
    name: Hdiv vulnerabilities check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy test agent log
        run: cp ./.github/workflows/hdivAgentLog.hlg.gz ${{github.workspace}}
      - name: Hdiv vulnerabilities check step
        uses: ./.github/actions/vuln-checker-action
        id: hdiv_vuln_checker
        env:
          hdiv.build.init: "0"
          hdiv.build.end: "1620298976976"
          hdiv.resource.folder: "."
          #hdiv.application.name: "spring-test-case"
          #hdiv.application.version: "3.0.0"
          #hdiv.triggers: '[{"count":0,"severity":"HIGH"}]'
     # - name: Get the output time
     #   run: echo "The time was ${{ steps.hdiv_vuln_checker.outputs.time }}"
      - name: Archive vulnerabilities json
        uses: actions/upload-artifact@v2
        with:
          name: hdiv-vuln-output-json
          path: vuln-checker-output.json
      - name: Archive vulnerabilities report
        uses: actions/upload-artifact@v2
        with:
          name: hdiv-vuln-report-html
          path: vuln-checker-report.html
