on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  hdiv_vuln_checker:
    runs-on: ubuntu-latest
    name: Hdiv vulnerabilities check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy test agent log
        run: cp hdivAgentLog.hlg ${{github.workspace}}
      - name: Hdiv vulnerabilities check step
        uses: ./.github/actions/vuln-checker-action
        id: hdiv_vuln_checker
        env:
          hdiv.build.init: "1590616800000"
          hdiv.build.end: "1690616800000"
          hdiv.resource.folder: "./target"
