on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  hdiv_vuln_checker:
    runs-on: ubuntu-latest
    name: Hdiv vulnerabilities check
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Hdiv vulnerabilities check step
        uses: ./.github/actions/vuln-checker-action
        id: hdiv_vuln_checker
